from django.urls import path

from apps.coffee.views import (
    AppEventCreateView,
    AppEventOCRResultsView,
    AppEventOCRView,
    AppEventResubmitView,
    AppEventSubmitView,
    AppOCRCorrectionView,
    AppPhotoCompleteView,
    AppPhotoChunkView,
    AppPhotoInitView,
    AppPlotCreateView,
    AppPointCreateView,
    CoffeeMobileLoginView,
    WebBGradeRuleCheckView,
    WebBGradeRuleDetailView,
    WebBGradeRuleListCreateView,
    WebEventListView,
    WebEventDetailView,
    WebEventBulkApproveView,
    WebEventBulkReturnView,
    WebEventReviewApproveView,
    WebEventReviewReturnView,
    WebExportJobCancelView,
    WebExportJobListCreateView,
    WebMetricDefinitionListCreateView,
    WebOCRCorrectionView,
    WebOCRJobListView,
    WebPhotoAnnotationListCreateView,
    WebPhotoListView,
    WebPhotoReviewView,
    WebProviderConfigListCreateView,
    WebProviderConfigDetailView,
    WebProviderConfigTestView,
    WebStatisticsPerformanceView,
    WebStatisticsProgressView,
    WebStatisticsQualityView,
)


urlpatterns = [
    path("auth/mobile-login/", CoffeeMobileLoginView.as_view()),
    path("app/plots/", AppPlotCreateView.as_view()),
    path("app/points/", AppPointCreateView.as_view()),
    path("app/events/", AppEventCreateView.as_view()),
    path("app/photos/init/", AppPhotoInitView.as_view()),
    path("app/photos/<str:photo_id>/chunks/<int:index>/", AppPhotoChunkView.as_view()),
    path("app/photos/<str:photo_id>/complete/", AppPhotoCompleteView.as_view()),
    path("app/events/<str:event_id>/ocr/", AppEventOCRView.as_view()),
    path("app/events/<str:event_id>/ocr-results/", AppEventOCRResultsView.as_view()),
    path("app/ocr-results/<str:ocr_result_id>/corrections/", AppOCRCorrectionView.as_view()),
    path("app/events/<str:event_id>/submit/", AppEventSubmitView.as_view()),
    path("app/events/<str:event_id>/resubmit/", AppEventResubmitView.as_view()),
    path("events/", WebEventListView.as_view()),
    path("events/<str:event_id>/", WebEventDetailView.as_view()),
    path("events/<str:event_id>/review/approve/", WebEventReviewApproveView.as_view()),
    path("events/<str:event_id>/review/return/", WebEventReviewReturnView.as_view()),
    path("events/review/bulk-approve/", WebEventBulkApproveView.as_view()),
    path("events/review/bulk-return/", WebEventBulkReturnView.as_view()),
    path("photos/", WebPhotoListView.as_view()),
    path("photos/<str:photo_id>/review/", WebPhotoReviewView.as_view()),
    path("photos/<str:photo_id>/annotations/", WebPhotoAnnotationListCreateView.as_view()),
    path("ocr/jobs/", WebOCRJobListView.as_view()),
    path("ocr-results/<str:ocr_result_id>/corrections/", WebOCRCorrectionView.as_view()),
    path("provider-configs/", WebProviderConfigListCreateView.as_view()),
    path("provider-configs/<int:provider_id>/", WebProviderConfigDetailView.as_view()),
    path("provider-configs/<int:provider_id>/toggle/", WebProviderConfigDetailView.as_view()),
    path("provider-configs/<int:provider_id>/test/", WebProviderConfigTestView.as_view()),
    path("metric-definitions/", WebMetricDefinitionListCreateView.as_view()),
    path("statistics/progress/", WebStatisticsProgressView.as_view()),
    path("statistics/quality/", WebStatisticsQualityView.as_view()),
    path("statistics/performance/", WebStatisticsPerformanceView.as_view()),
    path("exports/", WebExportJobListCreateView.as_view()),
    path("exports/<str:job_code>/cancel/", WebExportJobCancelView.as_view()),
    path("b-grade-rules/", WebBGradeRuleListCreateView.as_view()),
    path("b-grade-rules/<str:rule_code>/", WebBGradeRuleDetailView.as_view()),
    path("b-grade-rules/<str:rule_code>/toggle/", WebBGradeRuleDetailView.as_view()),
    path("b-grade-rules/<str:rule_code>/check/", WebBGradeRuleCheckView.as_view()),
]
