# Generated manually for the coffee collection domain baseline.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("plot_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Plot_ID")),
                ("task_code", models.CharField(db_index=True, max_length=64, verbose_name="任务编号")),
                ("name", models.CharField(max_length=128, verbose_name="地块名称")),
                ("admin_region", models.CharField(blank=True, max_length=255, null=True, verbose_name="行政区")),
                ("boundary_geojson", models.JSONField(default=dict, verbose_name="边界GeoJSON")),
                ("area_mu", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="面积(亩)")),
                ("area_calc_method", models.CharField(choices=[("geodesic", "椭球面积"), ("projected", "投影面积")], default="geodesic", max_length=32, verbose_name="面积计算方法")),
                ("coordinate_system", models.CharField(choices=[("gcj02", "GCJ-02"), ("wgs84", "WGS-84")], default="gcj02", max_length=16, verbose_name="坐标系")),
                ("source_type", models.CharField(choices=[("app_drawn", "App现场圈选"), ("web_created", "Web创建"), ("imported", "导入")], default="app_drawn", max_length=32, verbose_name="来源")),
                ("created_in_field", models.BooleanField(default=True, verbose_name="现场创建")),
                ("collector_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="采集员ID")),
                ("area_check_status", models.CharField(choices=[("not_checked", "未复核"), ("matched", "一致"), ("mismatch", "不一致"), ("adjusted", "已调整")], default="not_checked", max_length=32, verbose_name="面积复核状态")),
                ("review_status", models.CharField(choices=[("pending_review", "待复核"), ("confirmed", "已确认"), ("returned", "退回重圈"), ("adjusted", "已调整")], default="pending_review", max_length=32, verbose_name="复核状态")),
                ("reviewed_by", models.CharField(blank=True, max_length=64, null=True, verbose_name="复核人")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="复核时间")),
                ("status", models.CharField(default="active", max_length=32, verbose_name="状态")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={"verbose_name": "咖啡地块", "verbose_name_plural": "咖啡地块", "db_table": "dvadmin_coffee_plot"},
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("point_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Point_ID")),
                ("task_code", models.CharField(db_index=True, max_length=64, verbose_name="任务编号")),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12, verbose_name="经度")),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12, verbose_name="纬度")),
                ("altitude", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="海拔")),
                ("coordinate_system", models.CharField(choices=[("gcj02", "GCJ-02"), ("wgs84", "WGS-84")], default="gcj02", max_length=16, verbose_name="坐标系")),
                ("source_type", models.CharField(choices=[("app_selected", "App现场点选"), ("web_created", "Web创建"), ("imported", "导入")], default="app_selected", max_length=32, verbose_name="来源")),
                ("created_in_field", models.BooleanField(default=True, verbose_name="现场创建")),
                ("collector_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="采集员ID")),
                ("review_status", models.CharField(choices=[("pending_review", "待复核"), ("confirmed", "已确认"), ("returned", "退回重圈"), ("adjusted", "已调整")], default="pending_review", max_length=32, verbose_name="复核状态")),
                ("status", models.CharField(default="active", max_length=32, verbose_name="状态")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("plot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="points", to="coffee.plot", verbose_name="地块")),
            ],
            options={"verbose_name": "咖啡采集点", "verbose_name_plural": "咖啡采集点", "db_table": "dvadmin_coffee_point"},
        ),
        migrations.CreateModel(
            name="PlotBoundaryVersion",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                ("boundary_geojson", models.JSONField(default=dict, verbose_name="边界GeoJSON")),
                ("area_mu", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="面积(亩)")),
                ("area_calc_method", models.CharField(choices=[("geodesic", "椭球面积"), ("projected", "投影面积")], default="geodesic", max_length=32, verbose_name="面积计算方法")),
                ("coordinate_system", models.CharField(choices=[("gcj02", "GCJ-02"), ("wgs84", "WGS-84")], default="gcj02", max_length=16, verbose_name="坐标系")),
                ("source_type", models.CharField(choices=[("app_drawn", "App现场圈选"), ("web_created", "Web创建"), ("imported", "导入")], default="app_drawn", max_length=32, verbose_name="来源")),
                ("review_note", models.CharField(blank=True, max_length=255, null=True, verbose_name="复核说明")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("plot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="boundary_versions", to="coffee.plot", verbose_name="地块")),
            ],
            options={"verbose_name": "咖啡地块边界版本", "verbose_name_plural": "咖啡地块边界版本", "db_table": "dvadmin_coffee_plot_boundary_version", "unique_together": {("plot", "version")}},
        ),
        migrations.CreateModel(
            name="CollectionEvent",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("event_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Event_ID")),
                ("task_code", models.CharField(db_index=True, max_length=64, verbose_name="任务编号")),
                ("collector_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="采集员ID")),
                ("idempotency_key", models.CharField(max_length=128, unique=True, verbose_name="幂等键")),
                ("status", models.CharField(choices=[("draft", "草稿"), ("submitted", "已提交"), ("reviewing", "审核中"), ("approved", "通过"), ("returned", "退回")], default="draft", max_length=32, verbose_name="状态")),
                ("collected_at", models.DateTimeField(blank=True, null=True, verbose_name="采集时间")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="提交时间")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本")),
                ("manifest_hash", models.CharField(max_length=128, verbose_name="Manifest Hash")),
                ("location_snapshot", models.JSONField(blank=True, default=dict, verbose_name="定位快照")),
                ("weather_snapshot", models.JSONField(blank=True, default=dict, verbose_name="天气快照")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("plot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="coffee.plot", verbose_name="地块")),
                ("point", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="coffee.point", verbose_name="采集点")),
            ],
            options={"verbose_name": "咖啡采集事件", "verbose_name_plural": "咖啡采集事件", "db_table": "dvadmin_coffee_collection_event"},
        ),
        migrations.CreateModel(
            name="MeasurementRecord",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("device_no", models.CharField(max_length=64, verbose_name="设备编号")),
                ("measured_at", models.DateTimeField(blank=True, null=True, verbose_name="采集时间")),
                ("wind_speed", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="风速")),
                ("wind_direction", models.CharField(blank=True, max_length=32, null=True, verbose_name="风向")),
                ("air_temperature", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="空气温度")),
                ("air_humidity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="空气湿度")),
                ("atmospheric_pressure", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="大气压力")),
                ("rainfall", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="雨量")),
                ("soil_moisture", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="土壤湿度")),
                ("soil_temperature", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="土壤温度")),
                ("soil_salinity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="土壤盐分")),
                ("soil_ph", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="土壤PH值")),
                ("source_photo_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="来源Photo_ID")),
                ("ocr_result_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="OCR结果ID")),
                ("is_abnormal", models.BooleanField(default=False, verbose_name="异常")),
                ("remark", models.CharField(blank=True, max_length=255, null=True, verbose_name="备注")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="measurements", to="coffee.collectionevent", verbose_name="采集事件")),
                ("retake_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="coffee.measurementrecord", verbose_name="复测原记录")),
            ],
            options={"verbose_name": "咖啡设备采集数据", "verbose_name_plural": "咖啡设备采集数据", "db_table": "dvadmin_coffee_measurement_record"},
        ),
        migrations.CreateModel(
            name="EventFieldValue",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("field_code", models.CharField(max_length=64, verbose_name="字段编码")),
                ("field_label", models.CharField(max_length=64, verbose_name="字段名称")),
                ("value_text", models.CharField(blank=True, max_length=255, null=True, verbose_name="文本值")),
                ("value_number", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="数值")),
                ("value_json", models.JSONField(blank=True, default=dict, verbose_name="JSON值")),
                ("unit", models.CharField(blank=True, max_length=32, null=True, verbose_name="单位")),
                ("source_type", models.CharField(choices=[("manual", "人工输入"), ("ocr", "OCR回填"), ("device", "设备采集"), ("system", "系统生成")], default="manual", max_length=32, verbose_name="来源")),
                ("source_photo_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="来源Photo_ID")),
                ("ocr_result_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="OCR结果ID")),
                ("ocr_raw_value", models.CharField(blank=True, max_length=255, null=True, verbose_name="OCR原值")),
                ("ocr_confidence", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name="OCR置信度")),
                ("corrected_from", models.CharField(blank=True, max_length=255, null=True, verbose_name="修正前值")),
                ("correction_reason", models.CharField(blank=True, max_length=255, null=True, verbose_name="修正原因")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="field_values", to="coffee.collectionevent", verbose_name="采集事件")),
            ],
            options={"verbose_name": "咖啡采集字段值", "verbose_name_plural": "咖啡采集字段值", "db_table": "dvadmin_coffee_event_field_value"},
        ),
        migrations.AddIndex(
            model_name="eventfieldvalue",
            index=models.Index(fields=["event", "field_code", "version"], name="dvadmin_cof_event_i_091cac_idx"),
        ),
        migrations.AddIndex(
            model_name="eventfieldvalue",
            index=models.Index(fields=["event", "source_type"], name="dvadmin_cof_event_i_089374_idx"),
        ),
    ]
