# Generated by Django 4.2.14 on 2026-06-24 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAsset',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('photo_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Photo_ID')),
                ('category', models.CharField(choices=[('device_reading', '设备采集屏幕'), ('environment', '地块环境'), ('plant', '植株'), ('fruit', '果实'), ('label', '样品袋/标签'), ('extra', '异常补充')], max_length=32, verbose_name='照片分类')),
                ('original_file', models.CharField(blank=True, max_length=512, null=True, verbose_name='原图路径')),
                ('watermarked_file', models.CharField(blank=True, max_length=512, null=True, verbose_name='水印图路径')),
                ('sha256', models.CharField(max_length=128, verbose_name='原图SHA256')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='照片Metadata')),
                ('precheck_status', models.CharField(choices=[('pending', '待预检'), ('precheck_pass', '预检通过'), ('precheck_warning', '预检警告'), ('precheck_blocked', '预检阻断')], default='pending', max_length=32, verbose_name='预检状态')),
                ('review_status', models.CharField(choices=[('review_pending', '待审核'), ('approved', '已通过'), ('returned', '退回补拍'), ('voided', '已作废')], default='review_pending', max_length=32, verbose_name='审核状态')),
                ('immutable_status', models.CharField(choices=[('pending', '待锁定'), ('locked', '原图已锁定'), ('voided', '已作废')], default='pending', max_length=32, verbose_name='不可变状态')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传完成时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='coffee.collectionevent', verbose_name='采集事件')),
            ],
            options={
                'verbose_name': '咖啡照片资产',
                'verbose_name_plural': '咖啡照片资产',
                'db_table': 'dvadmin_coffee_photo_asset',
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('ocr_result_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='OCR结果ID')),
                ('provider', models.CharField(choices=[('paddleocr', 'PaddleOCR'), ('huawei_ocr', '华为OCR'), ('manual', '人工录入')], max_length=32, verbose_name='Provider')),
                ('status', models.CharField(choices=[('pending', '待识别'), ('running', '识别中'), ('success', '识别成功'), ('failed', '识别失败'), ('timeout', '识别超时'), ('manual', '人工录入')], default='pending', max_length=32, verbose_name='状态')),
                ('raw_response_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='原始响应引用')),
                ('raw_response_json', models.JSONField(blank=True, default=dict, verbose_name='原始响应JSON')),
                ('structured_json', models.JSONField(blank=True, default=dict, verbose_name='结构化识别结果')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='置信度')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='错误码')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='错误信息')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='coffee.photoasset', verbose_name='照片')),
            ],
            options={
                'verbose_name': '咖啡OCR结果',
                'verbose_name_plural': '咖啡OCR结果',
                'db_table': 'dvadmin_coffee_ocr_result',
            },
        ),
        migrations.CreateModel(
            name='OCRCorrection',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('field_name', models.CharField(max_length=64, verbose_name='字段名')),
                ('raw_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始值')),
                ('corrected_value', models.CharField(max_length=255, verbose_name='修正值')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='修正原因')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('corrected_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修正人')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='修正时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='coffee.ocrresult', verbose_name='OCR结果')),
            ],
            options={
                'verbose_name': '咖啡OCR修正',
                'verbose_name_plural': '咖啡OCR修正',
                'db_table': 'dvadmin_coffee_ocr_correction',
            },
        ),
        migrations.CreateModel(
            name='ProviderCallLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('provider_type', models.CharField(max_length=32, verbose_name='Provider类型')),
                ('provider_name', models.CharField(max_length=64, verbose_name='Provider名称')),
                ('request_id', models.CharField(db_index=True, max_length=128, verbose_name='请求ID')),
                ('target_type', models.CharField(max_length=32, verbose_name='目标类型')),
                ('target_id', models.CharField(db_index=True, max_length=64, verbose_name='目标ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=32, verbose_name='状态')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='耗时毫秒')),
                ('request_digest', models.CharField(blank=True, max_length=128, null=True, verbose_name='请求摘要')),
                ('response_digest', models.CharField(blank=True, max_length=128, null=True, verbose_name='响应摘要')),
                ('raw_response_ref', models.CharField(blank=True, max_length=128, null=True, verbose_name='原始响应引用')),
                ('error_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='错误码')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='调用时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '咖啡Provider调用日志',
                'verbose_name_plural': '咖啡Provider调用日志',
                'db_table': 'dvadmin_coffee_provider_call_log',
                'indexes': [models.Index(fields=['provider_type', 'status'], name='dvadmin_cof_provide_a4ae35_idx'), models.Index(fields=['target_type', 'target_id'], name='dvadmin_cof_target__866e32_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='photoasset',
            index=models.Index(fields=['event', 'category'], name='dvadmin_cof_event_i_18a2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='photoasset',
            index=models.Index(fields=['event', 'review_status'], name='dvadmin_cof_event_i_d7794b_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['photo', 'status'], name='dvadmin_cof_photo_i_94fb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['provider', 'status'], name='dvadmin_cof_provide_220851_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ocrcorrection',
            unique_together={('ocr_result', 'field_name', 'version')},
        ),
    ]
