# Generated by Django 4.2.14 on 2026-06-24 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0002_photoasset_ocrresult_ocrcorrection_providercalllog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('review_type', models.CharField(choices=[('event', '数据包审核'), ('photo', '照片审核')], default='event', max_length=32, verbose_name='审核类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('returned', '退回'), ('rechecking', '复核中')], default='pending', max_length=32, verbose_name='审核状态')),
                ('reviewer_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='审核员ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='审核结果')),
                ('return_reason', models.CharField(blank=True, max_length=128, null=True, verbose_name='退回原因')),
                ('return_items', models.JSONField(blank=True, default=list, verbose_name='退回项')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='coffee.collectionevent', verbose_name='采集事件')),
            ],
            options={
                'verbose_name': '咖啡质检审核',
                'verbose_name_plural': '咖啡质检审核',
                'db_table': 'dvadmin_coffee_quality_review',
                'indexes': [models.Index(fields=['event', 'review_type', 'version'], name='dvadmin_cof_event_i_d4dc36_idx'), models.Index(fields=['status', 'reviewed_at'], name='dvadmin_cof_status_f1b78d_idx')],
            },
        ),
    ]
